"""
Script para visualizar movimentos SMPLX gerados pelo GENMO.

Gera visualizações HTML interativas usando ScenepicVisualizer.
"""

import argparse
import numpy as np
import torch
from pathlib import Path
import sys

# Adicionar o diretório raiz ao path
sys.path.insert(0, str(Path(__file__).parent.parent))

from genmo.utils.vis.vis_scenepic import ScenepicVisualizer
from genmo.utils.pylogger import Log


def load_genmo_results(hmr4d_results_path):
    """
    Loads GENMO results.
    
    Args:
        hmr4d_results_path: Path to hmr4d_results.pt file
        
    Returns:
        dict: Dictionary with SMPLX parameters
    """
    if not Path(hmr4d_results_path).exists():
        raise FileNotFoundError(f"File not found: {hmr4d_results_path}")
    
    data = torch.load(hmr4d_results_path, map_location="cpu")
    
    if "smpl_params_global" not in data:
        raise ValueError(
            "File does not contain 'smpl_params_global'. "
            "Make sure the file was generated by GENMO."
        )
    
    return data


def prepare_smpl_seq(smpl_params, gender="neutral"):
    """
    Prepares data in the format expected by ScenepicVisualizer.
    
    Args:
        smpl_params: dict with SMPLX parameters
        gender: str, model gender
        
    Returns:
        dict: Data in the format expected by the visualizer
    """
    # Extract parameters
    body_pose = smpl_params["body_pose"]
    global_orient = smpl_params["global_orient"]
    transl = smpl_params["transl"]
    betas = smpl_params["betas"]
    
    # Convert to torch if necessary
    if isinstance(body_pose, np.ndarray):
        body_pose = torch.from_numpy(body_pose).float()
    if isinstance(global_orient, np.ndarray):
        global_orient = torch.from_numpy(global_orient).float()
    if isinstance(transl, np.ndarray):
        transl = torch.from_numpy(transl).float()
    if isinstance(betas, np.ndarray):
        betas = torch.from_numpy(betas).float()
    
    # If betas has shape (L, 10), use only the first frame
    if len(betas.shape) > 1:
        betas = betas[0]  # (10,)
    
    # Concatenate global_orient + body_pose to form complete pose
    # Format: pose = [global_orient (3), body_pose (63)] = (66,)
    pose = torch.cat([global_orient, body_pose], dim=1)  # (L, 66)
    
    # Prepare sequence in expected format
    smpl_seq = {
        "pose": pose,           # (L, 66)
        "trans": transl,        # (L, 3)
        "shape": betas[None],   # (1, 10) - expandir para batch
        "gender": gender,
    }
    
    return smpl_seq


def visualize_smplx(
    hmr4d_results_path,
    output_path,
    gender="neutral",
    smpl_model_dir=None,
    show_skeleton=True,
):
    """
    Generates HTML visualization of SMPLX motion.
    
    Args:
        hmr4d_results_path: Path to hmr4d_results.pt
        output_path: Output path for HTML file
        gender: Model gender
        smpl_model_dir: Directory with SMPL models (optional)
        show_skeleton: If True, shows skeleton in addition to mesh
    """
    # Set default SMPL models directory if not provided
    if smpl_model_dir is None:
        smpl_model_dir = "inputs/checkpoints/body_models/smpl"
    
    print("=" * 60)
    print("Visualização SMPLX")
    print("=" * 60)
    print(f"Input: {hmr4d_results_path}")
    print(f"Output: {output_path}")
    print(f"Gender: {gender}")
    print()
    
    try:
        # 1. Load results
        print("1. Loading GENMO results...")
        genmo_data = load_genmo_results(hmr4d_results_path)
        smpl_params = genmo_data["smpl_params_global"]
        print(f"   ✓ Loaded: {len(smpl_params['body_pose'])} frames")
        
        # 2. Prepare data
        print("2. Preparing data for visualization...")
        smpl_seq = prepare_smpl_seq(smpl_params, gender=gender)
        print("   ✓ Data prepared")
        
        # 3. Create visualizer
        print("3. Initializing visualizer...")
        visualizer = ScenepicVisualizer(
            smpl_model_dir=smpl_model_dir,
            device="cpu",  # Use CPU for visualization
            show_skeleton_jpos=show_skeleton,
        )
        print("   ✓ Visualizador inicializado")
        
        # 4. Gerar visualização
        print("4. Gerando visualização HTML...")
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        visualizer.vis_smpl_scene(smpl_seq, str(output_path))
        print(f"   ✓ Visualização salva: {output_path}")
        
        print()
        print("=" * 60)
        print("✓ Visualização gerada com sucesso!")
        print("=" * 60)
        print()
        print(f"Abra o arquivo no navegador: {output_path.absolute()}")
        
    except Exception as e:
        print()
        print("=" * 60)
        print("✗ Erro durante a visualização:")
        print(f"  {str(e)}")
        print("=" * 60)
        import traceback
        traceback.print_exc()
        raise


def main():
    parser = argparse.ArgumentParser(
        description="Visualiza movimentos SMPLX gerados pelo GENMO"
    )
    parser.add_argument(
        "--input",
        type=str,
        required=True,
        help="Caminho para o arquivo hmr4d_results.pt gerado pelo GENMO",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Caminho de saída para o arquivo HTML (padrão: <input_dir>/visualization.html)",
    )
    parser.add_argument(
        "--gender",
        type=str,
        default="neutral",
        choices=["male", "female", "neutral"],
        help="Gênero do modelo (deve corresponder ao usado no GENMO)",
    )
    parser.add_argument(
        "--smpl_model_dir",
        type=str,
        default=None,
        help="Diretório com modelos SMPL (padrão: inputs/checkpoints/body_models/smpl)",
    )
    parser.add_argument(
        "--no-skeleton",
        action="store_true",
        help="Não mostrar esqueleto, apenas malha",
    )
    
    args = parser.parse_args()
    
    # Definir output padrão se não fornecido
    if args.output is None:
        input_path = Path(args.input)
        args.output = input_path.parent / "visualization.html"
    
    visualize_smplx(
        args.input,
        args.output,
        gender=args.gender,
        smpl_model_dir=args.smpl_model_dir,
        show_skeleton=not args.no_skeleton,
    )


if __name__ == "__main__":
    main()

